# Generated by Django 4.0.1 on 2024-06-01 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20211006_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='cat_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='cat_gar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories', to_field='cat_name'),
        ),
    ]
