# Generated by Django 4.0.1 on 2024-06-01 08:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_categories_cat_name_alter_item_cat_gar'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category_name',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='item_cat_name', to='shop.categories', to_field='cat_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='cat_gar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categories'),
        ),
    ]
