# Generated by Django 4.0.1 on 2024-06-04 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_catsales_category_name_alter_item_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catsales',
            old_name='category_name',
            new_name='catgars_name',
        ),
    ]
