# Generated by Django 4.0.1 on 2024-06-04 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_rename_category_name_catsales_catgars_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catsales',
            name='catgars_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profit_cat_name', to='shop.item', to_field='category_name'),
        ),
    ]
