# Generated by Django 4.0.1 on 2024-06-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_catsales_catgars_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catsales',
            name='catgars_name',
        ),
    ]
